package api

import (
	"bytes"
	"fmt"
	"net/http"
	"text/template"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/trustos/pulumi-ui/internal/nebula"
)

// nebulaConfigTmpl is the Nebula YAML config template for user machines joining the mesh.
var nebulaConfigTmpl = template.Must(template.New("nebula-config").Parse(`# Nebula mesh configuration for stack "{{ .StackName }}"
# Generated by pulumi-ui — import into Nebula on your local machine.
#
# Quick start:
#   1. Install Nebula: brew install nebula  (or download from https://github.com/slackhq/nebula/releases)
#   2. Save this file as nebula-config.yml
#   3. Run: sudo nebula -config nebula-config.yml
#   4. Access nodes via their Nebula IPs (e.g. ssh ubuntu@{{ .FirstNodeIP }})
#
# Your Nebula IP: {{ .UserIP }}
# Subnet: {{ .Subnet }}

pki:
  ca: |
{{ .CACert }}
  cert: |
{{ .UserCert }}
  key: |
{{ .UserKey }}

static_host_map:
{{ .StaticHostMap }}

lighthouse:
  am_lighthouse: false
  hosts: []

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true
  respond: true

tun:
  disabled: false

firewall:
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
    - port: 22
      proto: tcp
      host: any
`))

// DownloadMeshConfig generates a Nebula config file that allows a user's local
// machine to join the stack's mesh network. Issues a fresh user certificate
// signed by the stack's CA.
func (h *NetworkHandler) DownloadMeshConfig(w http.ResponseWriter, r *http.Request) {
	stackName := chi.URLParam(r, "name")

	// Get stack connection (CA cert/key, subnet, agent IPs)
	conn, err := h.ConnStore.Get(stackName)
	if err != nil || conn == nil {
		http.Error(w, "stack connection not found", http.StatusNotFound)
		return
	}

	if conn.NebulaCACert == nil || conn.NebulaCAKey == nil {
		http.Error(w, "stack has no Nebula PKI", http.StatusNotFound)
		return
	}

	// Allocate user IP — use host index 200 (well above the 10 pre-generated node certs)
	// to avoid collisions. Each download gets the same IP (stateless — no DB tracking).
	// For multi-user support, this would need a counter in the DB.
	userIP, err := nebula.SubnetIP(conn.NebulaSubnet, 200)
	if err != nil {
		http.Error(w, "failed to allocate user IP: "+err.Error(), http.StatusInternalServerError)
		return
	}

	// Issue user certificate
	userCert, err := nebula.IssueCert(
		conn.NebulaCACert,
		conn.NebulaCAKey,
		"user-local",
		userIP,
		[]string{"user"},
		365*24*time.Hour,
	)
	if err != nil {
		http.Error(w, "failed to issue user cert: "+err.Error(), http.StatusInternalServerError)
		return
	}

	// Build static_host_map entries
	var staticMap bytes.Buffer

	// Add all deployed nodes from node_certs
	var firstNodeIP string
	if h.NodeCertStore != nil {
		nodes, _ := h.NodeCertStore.ListForStack(stackName)
		for _, node := range nodes {
			if node.AgentRealIP == nil || *node.AgentRealIP == "" {
				continue
			}
			nebulaIP := node.NebulaIP
			// Strip /24 suffix for the static_host_map key
			if idx := bytes.IndexByte([]byte(nebulaIP), '/'); idx > 0 {
				nebulaIP = nebulaIP[:idx]
			}
			realIP := *node.AgentRealIP
			fmt.Fprintf(&staticMap, "  '%s': ['%s']\n", nebulaIP, realIP)
			if firstNodeIP == "" {
				firstNodeIP = nebulaIP
			}
		}
	}

	// Fallback to legacy single-agent IP if no node certs
	if staticMap.Len() == 0 && conn.AgentRealIP != nil && *conn.AgentRealIP != "" {
		agentNebulaIP := "10.42.0.2" // default
		if conn.AgentNebulaIP != nil {
			agentNebulaIP = *conn.AgentNebulaIP
		}
		fmt.Fprintf(&staticMap, "  '%s': ['%s:41820']\n", agentNebulaIP, *conn.AgentRealIP)
		firstNodeIP = agentNebulaIP
	}

	if firstNodeIP == "" {
		firstNodeIP = "10.42.x.2"
	}

	// Indent PEM blocks for YAML embedding (4 spaces)
	indentPEM := func(pem []byte) string {
		var buf bytes.Buffer
		for _, line := range bytes.Split(pem, []byte("\n")) {
			if len(line) > 0 {
				buf.WriteString("    ")
				buf.Write(line)
				buf.WriteByte('\n')
			}
		}
		return buf.String()
	}

	// Render config
	var config bytes.Buffer
	data := struct {
		StackName    string
		UserIP       string
		Subnet       string
		FirstNodeIP  string
		CACert       string
		UserCert     string
		UserKey      string
		StaticHostMap string
	}{
		StackName:    stackName,
		UserIP:       userIP.Addr().String(),
		Subnet:       conn.NebulaSubnet,
		FirstNodeIP:  firstNodeIP,
		CACert:       indentPEM(conn.NebulaCACert),
		UserCert:     indentPEM(userCert.CertPEM),
		UserKey:      indentPEM(userCert.KeyPEM),
		StaticHostMap: staticMap.String(),
	}

	if err := nebulaConfigTmpl.Execute(&config, data); err != nil {
		http.Error(w, "failed to render config: "+err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/x-yaml")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="nebula-%s.yml"`, stackName))
	w.Write(config.Bytes())
}
