/**
 * Solution cards define pre-configured deployment recipes.
 * Each card maps to a program + pre-selected applications with
 * minimal user input. The derivedConfig function transforms user
 * fields into the full config + appConfig needed by putStack().
 */

export interface SolutionField {
  key: string;
  label: string;
  type: 'text' | 'email';
  required: boolean;
  placeholder?: string;
  description?: string;
}

export interface SolutionCard {
  id: string;
  name: string;
  description: string;
  icon: string;             // emoji or short text
  program: string;          // program name (e.g., "nomad-cluster")
  applications: string[];   // app keys to pre-select
  userFields: SolutionField[];
  /** Default infra config overrides (merged with program defaults) */
  configOverrides?: Record<string, string>;
  /** Transform user input into full putStack parameters */
  deriveConfig: (input: Record<string, string>) => {
    config: Record<string, string>;
    applications: Record<string, boolean>;
    appConfig: Record<string, string>;
  };
}

// ── Solution: NocoBase ──────────────────────────────────────────────────

const nocobaseSolution: SolutionCard = {
  id: 'nocobase',
  name: 'NocoBase',
  description: 'No-code platform with PostgreSQL, Traefik ingress, and automated backups on a Nomad cluster',
  icon: '🧩',
  program: 'nomad-cluster',
  applications: ['traefik', 'postgres', 'postgres-backup', 'nocobase'],
  configOverrides: { nodeCount: '1' },
  userFields: [
    { key: 'email', label: 'Email', type: 'email', required: true, placeholder: 'admin@example.com', description: 'Used for Let\'s Encrypt certificates and pgAdmin login' },
    { key: 'domain', label: 'NocoBase Domain', type: 'text', required: false, placeholder: 'nocobase.example.com', description: 'Optional — for HTTPS access. Without it, use port forwarding.' },
  ],
  deriveConfig: (input) => {
    const domain = input.domain?.trim() || '';
    const baseDomain = domain.includes('.') ? domain.split('.').slice(1).join('.') : domain;
    const appConfig: Record<string, string> = {
      'traefik.acmeEmail': input.email || '',
      'postgres.dbUser': 'admin',
      'postgres.pgadminEmail': input.email || '',
      'nocobase.dbUser': 'admin',
      'nocobase.dbName': 'nocobase',
      // dbPassword and appKey are auto-generated by the deployer
    };
    if (domain) {
      appConfig['nocobase.domain'] = domain;
      appConfig['postgres.pgadminDomain'] = `pgadmin.${baseDomain}`;
    }
    return {
      config: { nodeCount: '1' },
      applications: {
        traefik: true,
        postgres: true,
        'postgres-backup': true,
        nocobase: true,
      },
      appConfig,
    };
  },
};

// ── Solution: Nomad Cluster (infra only) ────────────────────────────────

const nomadClusterSolution: SolutionCard = {
  id: 'nomad-cluster',
  name: 'Nomad Cluster',
  description: 'Docker + Consul + Nomad infrastructure on OCI ARM instances. Add applications later.',
  icon: '⚡',
  program: 'nomad-cluster',
  applications: ['traefik'],
  userFields: [
    { key: 'email', label: 'Email', type: 'email', required: true, placeholder: 'admin@example.com', description: 'Used for Let\'s Encrypt certificates' },
  ],
  deriveConfig: (input) => ({
    config: {},
    applications: { traefik: true },
    appConfig: {
      'traefik.acmeEmail': input.email || '',
    },
  }),
};

// ── Export ───────────────────────────────────────────────────────────────

export const solutions: SolutionCard[] = [
  nocobaseSolution,
  nomadClusterSolution,
];
